#ifndef __KEY_DEF__
#define __KEY_DEF__

#include "key.h"

#define GK(key) new GeneralKey(key)
#define NA NULL

#define _1                GK(KEY_1)
#define _2                GK(KEY_2)
#define _3                GK(KEY_3)
#define _4                GK(KEY_4)
#define _5                GK(KEY_5)
#define _6                GK(KEY_6)
#define _7                GK(KEY_7)
#define _8                GK(KEY_8)
#define _9                GK(KEY_9)
#define _0                GK(KEY_0)

#define _A                GK(KEY_A)
#define _B                GK(KEY_B)
#define _C                GK(KEY_C)
#define _D                GK(KEY_D)
#define _E                GK(KEY_E)
#define _F                GK(KEY_F)
#define _G                GK(KEY_G)
#define _H                GK(KEY_H)
#define _I                GK(KEY_I)
#define _J                GK(KEY_J)
#define _K                GK(KEY_K)
#define _L                GK(KEY_L)
#define _M                GK(KEY_M)
#define _N                GK(KEY_N)
#define _O                GK(KEY_O)
#define _P                GK(KEY_P)
#define _Q                GK(KEY_Q)
#define _R                GK(KEY_R)
#define _S                GK(KEY_S)
#define _T                GK(KEY_T)
#define _U                GK(KEY_U)
#define _V                GK(KEY_V)
#define _W                GK(KEY_W)
#define _X                GK(KEY_X)
#define _Y                GK(KEY_Y)
#define _Z                GK(KEY_Z)

#define _MINUS            GK(KEY_MINUS)
#define _EQUAL            GK(KEY_EQUAL)
#define _BACKSLASH        GK(KEY_BACKSLASH)
#define _SLASH            GK(KEY_SLASH)
#define _COMMA            GK(KEY_COMMA)
#define _PERIOD           GK(KEY_PERIOD)
#define _TAB              GK(KEY_TAB)
#define _SEMICOLON        GK(KEY_SEMICOLON)
#define _LEFT_BRACE       GK(KEY_LEFT_BRACE)
#define _RIGHT_BRACE      GK(KEY_RIGHT_BRACE)
#define _ACCENT           GK(KEY_TILDE)

#define _LEFT_ARROW       GK(KEY_LEFT_ARROW)
#define _RIGHT_ARROW      GK(KEY_RIGHT_ARROW )
#define _DOWN_ARROW       GK(KEY_DOWN_ARROW)
#define _UP_ARROW         GK(KEY_UP_ARROW)

#define _LEFT_SHIFT       GK(KEY_LEFT_SHIFT)
#define _RIGHT_SHIFT      GK(KEY_RIGHT_SHIFT)
#define _LEFT_ALT         GK(KEY_LEFT_ALT)
#define _RIGHT_ALT        GK(KEY_RIGHT_ALT )
#define _LEFT_CTRL        GK(KEY_LEFT_CTRL)
#define _RIGHT_CTRL       GK(KEY_RIGHT_CTRL)
#define _LEFT_GUI         GK(KEY_LEFT_GUI )
#define _RIGHT_GUI        GK(KEY_RIGHT_GUI)
#define _ESC              GK(KEY_ESC)
#define _CAPS_LOCK        GK(KEY_CAPS_LOCK)

#define _RETURN           GK(KEY_RETURN)
#define _SPACE            GK(KEY_SPACE)
#define _BACKSPACE        GK(KEY_BACKSPACE)

#define _DELETE           GK(KEY_DELETE)
#define _HOME             GK(KEY_HOME)
#define _END              GK(KEY_END)
#define _PAGE_UP          GK(KEY_PAGE_UP)
#define _PAGE_DOWN        GK(KEY_PAGE_DOWN)

#define _PRINTSCREEN	  GK(KEY_PRINTSCREEN)
#define _NUM_LOCK	  GK(KEY_NUM_LOCK)
#define _MENU		  GK(KEY_MENU)

#define _F1               GK(KEY_F1)
#define _F2               GK(KEY_F2)
#define _F3               GK(KEY_F3)
#define _F4               GK(KEY_F4)
#define _F5               GK(KEY_F5)
#define _F6               GK(KEY_F6)
#define _F7               GK(KEY_F7)
#define _F8               GK(KEY_F8)
#define _F9               GK(KEY_F9)
#define _F10              GK(KEY_F10)
#define _F11              GK(KEY_F11)
#define _F12              GK(KEY_F12)

#endif
